include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    directives_ordering: false

analyzer:
  exclude:
    - "**/*.g.dart"
