name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  collection: ^1.19.1
  shared_preferences: ^2.5.3
  very_good_analysis: ^7.0.0
  import_sorter: ^4.6.0
  camera: ^0.11.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  gal: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/
    - .env

  fonts:
     - family: WinkySans
       fonts:
         - asset: fonts/WinkySans-VariableFont_wght.ttf
     - family: Montserrat
       fonts:
         - asset: fonts/Montserrat-VariableFont_wght.ttf
     - family: Inter
       fonts:
         - asset: fonts/Inter-VariableFont_opsz,wght.ttf
